#!/usr/bin/env bash

# Install Nginx if not already installed (assuming you have the 1-install_nginx_web_server script)
bash 1-install_nginx_web_server.sh

# Create a configuration file for the redirection
echo "server {
    listen 80;
    server_name robinsonvictor.tech;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Additional server configurations if needed

}" | sudo tee /etc/nginx/sites-available/redirect_me > /dev/null

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo service nginx reload

