#!/usr/bin/env bash

# Install Nginx if not already installed (assuming you have the 1-install_nginx_web_server script)
bash 1-install_nginx_web_server.sh

# Create a configuration file for the custom 404 page
echo "server {
    listen 80;
    server_name robinsonvictor.tech;

    error_page 404 /not_found;

    location /not_found {
        return 404 \"Ceci n'est pas une page\";
    }

    # Additional server configurations if needed

}" | sudo tee /etc/nginx/sites-available/not_found_page_404 > /dev/null

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/not_found_page_404 /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo service nginx reload

