#!/usr/bin/env bash
# Displays listening ports:
    # That only shows listening sockets.
    # That shows the PID and name of the program to which the socket belong.

sudo netstat --listening --programs
